import { TeamMemberCard } from './types'

export const TRIBE_TEAM_MEMBERS: TeamMemberCard[] = [
  {
    "id": "ca-1",
    "slug": "nithin-reddy-jeeru",
    "name": "Nithin Reddy Jeeru",
    "teamIdBadge": "ST-CA-01",
    "role": "Lead Campus Ambassador & Convener",
    "branch": "Mechanical Engineering \u00b7 Class of 2029",
    "college": "Anil Neerukonda Institute of Technology and Sciences",
    "location": "Tagarapuvalasa",
    "phone": "7.416777852E9",
    "experience": "Official Student Tribe College Ambassador representing Anil Neerukonda Institute of Technology and Sciences (Tagarapuvalasa). Spearheading Tribeverse engagement and campus community leadership.",
    "avatarUrl": "/id-cards-v2/nithin-reddy-jeeru-front.png",
    "backAvatarUrl": "/id-cards-v2/nithin-reddy-jeeru-back.png",
    "linkedinUrl": "https://www.linkedin.com/in/nithin-reddy-jeeru-a68b35380?utm_source=share_via&utm_content=profile&utm_medium=member_android",
    "instagramUrl": "https://www.instagram.com/nithin_reddy__06_?stkn=MWRlczF4ZTRxY3c5aw==",
    "category": "Lead"
  },
  {
    "id": "ca-2",
    "slug": "varun-ramisetty",
    "name": "Varun Ramisetty",
    "teamIdBadge": "ST-CA-02",
    "role": "Campus Ambassador",
    "branch": "Mechanical Engineering \u00b7 Class of 2029",
    "college": "Anil Neerukonda Institute of Technology and Sciences",
    "location": "P.M.Palem",
    "phone": "9.86607847E9",
    "experience": "Official Student Tribe College Ambassador representing Anil Neerukonda Institute of Technology and Sciences (P.M.Palem). Spearheading Tribeverse engagement and campus community leadership.",
    "avatarUrl": "/id-cards-v2/varun-ramisetty-front.png",
    "backAvatarUrl": "/id-cards-v2/varun-ramisetty-back.png",
    "linkedinUrl": "https://www.linkedin.com/in/varun-ramisetty-2oo8?utm_source=share_via&utm_content=profile&utm_medium=member_android",
    "instagramUrl": "https://www.instagram.com/varun_v_2008?stkn=eW4zZmNya2cxZWlz",
    "category": "Operations"
  },
  {
    "id": "ca-3",
    "slug": "praveen-raj-savarapu",
    "name": "Praveen Raj Savarapu",
    "teamIdBadge": "ST-CA-03",
    "role": "Campus Ambassador",
    "branch": "Mechanical Engineering \u00b7 Class of 2029",
    "college": "Anil Neerukonda Institute of Technology and Sciences",
    "location": "Kancharapalem",
    "phone": "8.341374037E9",
    "experience": "Official Student Tribe College Ambassador representing Anil Neerukonda Institute of Technology and Sciences (Kancharapalem). Spearheading Tribeverse engagement and campus community leadership.",
    "avatarUrl": "/id-cards-v2/praveen-raj-savarapu-front.png",
    "backAvatarUrl": "/id-cards-v2/praveen-raj-savarapu-back.png",
    "linkedinUrl": "https://www.linkedin.com/in/praveen-raj-savarapu-b418a6395?utm_source=share_via&utm_content=profile&utm_medium=member_android",
    "instagramUrl": "https://www.instagram.com/the_praaveen?stkn=N2ZsaXd0ZHZuNnJi",
    "category": "Operations"
  },
  {
    "id": "ca-4",
    "slug": "karakana-siva-sai-anudeep",
    "name": "Karakana Siva Sai Anudeep",
    "teamIdBadge": "ST-CA-04",
    "role": "Campus Ambassador",
    "branch": "Mechanical Engineering \u00b7 Class of 2029",
    "college": "Anil Neerukonda Institute of Technology and Sciences",
    "location": "Akkayapalem",
    "phone": "7.893956533E9",
    "experience": "Official Student Tribe College Ambassador representing Anil Neerukonda Institute of Technology and Sciences (Akkayapalem). Spearheading Tribeverse engagement and campus community leadership.",
    "avatarUrl": "/id-cards-v2/karakana-siva-sai-anudeep-front.png",
    "backAvatarUrl": "/id-cards-v2/karakana-siva-sai-anudeep-back.png",
    "linkedinUrl": "https://www.linkedin.com/in/anudeep-karakana-984b23420?utm_source=share_via&utm_content=profile&utm_medium=member_android",
    "instagramUrl": "https://www.instagram.com/anudeeep.3?stkn=MWZxNmhvdTJxYnhhaQ==",
    "category": "Operations"
  },
  {
    "id": "ca-5",
    "slug": "kotni-reshma",
    "name": "Kotni Reshma",
    "teamIdBadge": "ST-CA-05",
    "role": "Campus Ambassador",
    "branch": "CSE (Computer Science) \u00b7 Class of 2028",
    "college": "Anil Neerukonda Institute of Technology and sciences",
    "location": "Sangivalasa",
    "phone": "8.790726339E9",
    "experience": "Official Student Tribe College Ambassador representing Anil Neerukonda Institute of Technology and sciences (Sangivalasa). Spearheading Tribeverse engagement and campus community leadership.",
    "avatarUrl": "/id-cards-v2/kotni-reshma-front.png",
    "backAvatarUrl": "/id-cards-v2/kotni-reshma-back.png",
    "linkedinUrl": "https://www.linkedin.com/in/reshma-kotni-b85660321/",
    "instagramUrl": "https://www.instagram.com/reshma__kotni_/",
    "category": "Core"
  },
  {
    "id": "ca-6",
    "slug": "kokkili-laxmi",
    "name": "Kokkili Laxmi",
    "teamIdBadge": "ST-CA-06",
    "role": "Campus Ambassador",
    "branch": "CSE (Computer Science) \u00b7 Class of 2028",
    "college": "Anil Neerukonda Institute of Technology and sciences",
    "location": "Sangivalasa",
    "phone": "9.491521412E9",
    "experience": "Official Student Tribe College Ambassador representing Anil Neerukonda Institute of Technology and sciences (Sangivalasa). Spearheading Tribeverse engagement and campus community leadership.",
    "avatarUrl": "/id-cards-v2/kokkili-laxmi-front.png",
    "backAvatarUrl": "/id-cards-v2/kokkili-laxmi-back.png",
    "linkedinUrl": "https://www.linkedin.com/in/laxmikokkili1221",
    "instagramUrl": null,
    "category": "Core"
  },
  {
    "id": "ca-7",
    "slug": "jyostna-mayee-sahu",
    "name": "Jyostna Mayee Sahu",
    "teamIdBadge": "ST-CA-07",
    "role": "Campus Ambassador",
    "branch": "CSE (Computer Science) \u00b7 Class of 2028",
    "college": "Anil Neerukonda Institute of Technology and sciences",
    "location": "Tagarapuvalasa",
    "phone": "9.03056903E9",
    "experience": "Official Student Tribe College Ambassador representing Anil Neerukonda Institute of Technology and sciences (Tagarapuvalasa). Spearheading Tribeverse engagement and campus community leadership.",
    "avatarUrl": "/id-cards-v2/jyostna-mayee-sahu-front.png",
    "backAvatarUrl": "/id-cards-v2/jyostna-mayee-sahu-back.png",
    "linkedinUrl": "https://www.linkedin.com/in/jyostnamayeesahu",
    "instagramUrl": null,
    "category": "Core"
  },
  {
    "id": "ca-8",
    "slug": "karubothu-yaswanth",
    "name": "Karubothu Yaswanth",
    "teamIdBadge": "ST-CA-08",
    "role": "Campus Ambassador",
    "branch": "Mechanical Engineering \u00b7 Class of 2029",
    "college": "Anil Neerukonda Institute of Technology and sciences",
    "location": "Pm palem",
    "phone": "9.966730844E9",
    "experience": "Official Student Tribe College Ambassador representing Anil Neerukonda Institute of Technology and sciences (Pm palem). Spearheading Tribeverse engagement and campus community leadership.",
    "avatarUrl": "/id-cards-v2/karubothu-yaswanth-front.png",
    "backAvatarUrl": "/id-cards-v2/karubothu-yaswanth-back.png",
    "linkedinUrl": "https://www.linkedin.com/in/yaswanth-k-02562b3b0?utm_source=share_via&utm_content=profile&utm_medium=member_android",
    "instagramUrl": "https://www.instagram.com/yaswanth__000?stkn=MXE3OHo4eGh2MDMwZg==&utm_source=ig_contact_invite",
    "category": "Operations"
  },
  {
    "id": "ca-9",
    "slug": "pilla-purnendra-pathrudu",
    "name": "Pilla Purnendra Pathrudu",
    "teamIdBadge": "ST-CA-09",
    "role": "Campus Ambassador",
    "branch": "Mechanical Engineering \u00b7 Class of 2029",
    "college": "Anil Neerukonda Institute of Technology and sciences",
    "location": "pendurthi",
    "phone": "8.309290045E9",
    "experience": "Official Student Tribe College Ambassador representing Anil Neerukonda Institute of Technology and sciences (pendurthi). Spearheading Tribeverse engagement and campus community leadership.",
    "avatarUrl": "/id-cards-v2/pilla-purnendra-pathrudu-front.png",
    "backAvatarUrl": "/id-cards-v2/pilla-purnendra-pathrudu-back.png",
    "linkedinUrl": "https://www.linkedin.com/in/purnendra-pilla-a2a0ba3a0?utm_source=share_via&utm_content=profile&utm_medium=member_android",
    "instagramUrl": "https://www.instagram.com/mr__devil53?stkn=MW8yZ3FoN3hueGc2dw==",
    "category": "Operations"
  },
  {
    "id": "ca-10",
    "slug": "boddepalli-somanaadhan",
    "name": "Boddepalli Somanaadhan",
    "teamIdBadge": "ST-CA-10",
    "role": "Campus Ambassador",
    "branch": "ECE (Electronics & Comm) \u00b7 Class of 2029",
    "college": "Anil Neerukonda Institute of Technology and Sciences",
    "location": "Tagarapuvalasa",
    "phone": "9.491263939E9",
    "experience": "Official Student Tribe College Ambassador representing Anil Neerukonda Institute of Technology and Sciences (Tagarapuvalasa). Spearheading Tribeverse engagement and campus community leadership.",
    "avatarUrl": "/id-cards-v2/boddepalli-somanaadhan-front.png",
    "backAvatarUrl": "/id-cards-v2/boddepalli-somanaadhan-back.png",
    "linkedinUrl": "https://www.linkedin.com/in/somanaadhan-boddepalli-017080396?utm_source=share_via&utm_content=profile&utm_medium=member_android",
    "instagramUrl": "https://www.instagram.com/somu_boddepalli?stkn=bmhybjd6YTFoMWk4",
    "category": "Tech"
  },
  {
    "id": "ca-11",
    "slug": "raghupatruni-santhwana",
    "name": "Raghupatruni Santhwana",
    "teamIdBadge": "ST-CA-11",
    "role": "Campus Ambassador",
    "branch": "IT (Information Technology) \u00b7 Class of 2029",
    "college": "Anil Neerukonda Institute of Technology and sciences",
    "location": "srikakulam",
    "phone": "9.391190959E9",
    "experience": "Official Student Tribe College Ambassador representing Anil Neerukonda Institute of Technology and sciences (srikakulam). Spearheading Tribeverse engagement and campus community leadership.",
    "avatarUrl": "/id-cards-v2/raghupatruni-santhwana-front.png",
    "backAvatarUrl": "/id-cards-v2/raghupatruni-santhwana-back.png",
    "linkedinUrl": "https://www.linkedin.com/in/santhwana-undefined-808b02396?utm_source=share_via&utm_content=profile&utm_medium=member_android",
    "instagramUrl": "https://www.instagram.com/santhwana_sagar?stkn=cnQyb3l1aXZwaHIx",
    "category": "Core"
  },
  {
    "id": "ca-12",
    "slug": "krovvidi-sameera",
    "name": "Krovvidi Sameera",
    "teamIdBadge": "ST-CA-12",
    "role": "Campus Ambassador",
    "branch": "CSE (AI & ML) \u00b7 Class of 2029",
    "college": "Anil Neerukonda Institute of technology and sciences",
    "location": "kopperla",
    "phone": "9.381316553E9",
    "experience": "Official Student Tribe College Ambassador representing Anil Neerukonda Institute of technology and sciences (kopperla). Spearheading Tribeverse engagement and campus community leadership.",
    "avatarUrl": "/id-cards-v2/krovvidi-sameera-front.png",
    "backAvatarUrl": "/id-cards-v2/krovvidi-sameera-back.png",
    "linkedinUrl": "https://www.linkedin.com/in/sameera-k-6133b5400?utm_source=share_via&utm_content=profile&utm_medium=member_android",
    "instagramUrl": null,
    "category": "Design"
  },
  {
    "id": "ca-13",
    "slug": "kondala-sonali",
    "name": "Kondala Sonali",
    "teamIdBadge": "ST-CA-13",
    "role": "Campus Ambassador",
    "branch": "CSE (AI & ML) \u00b7 Class of 2029",
    "college": "Anil Neerukonda Institute of technology and sciences",
    "location": "srikakulam",
    "phone": "7.386544538E9",
    "experience": "Official Student Tribe College Ambassador representing Anil Neerukonda Institute of technology and sciences (srikakulam). Spearheading Tribeverse engagement and campus community leadership.",
    "avatarUrl": "/id-cards-v2/kondala-sonali-front.png",
    "backAvatarUrl": "/id-cards-v2/kondala-sonali-back.png",
    "linkedinUrl": "https://www.linkedin.com/in/sonali-k-b67192401?utm_source=share_via&utm_content=profile&utm_medium=member_android",
    "instagramUrl": "https://www.instagram.com/sonalirohan_?stkn=bml0NnE4NXBoejRy",
    "category": "Design"
  },
  {
    "id": "ca-14",
    "slug": "m-dhanush-kumar",
    "name": "M.dhanush Kumar",
    "teamIdBadge": "ST-CA-14",
    "role": "Campus Ambassador",
    "branch": "CSE (AI & ML) \u00b7 Class of 2029",
    "college": "Anil neerukonda institute of technology and sciences",
    "location": "sangivalasa",
    "phone": "6.303321896E9",
    "experience": "Official Student Tribe College Ambassador representing Anil neerukonda institute of technology and sciences (sangivalasa). Spearheading Tribeverse engagement and campus community leadership.",
    "avatarUrl": "/id-cards-v2/m-dhanush-kumar-front.png",
    "backAvatarUrl": "/id-cards-v2/m-dhanush-kumar-back.png",
    "linkedinUrl": "https://www.linkedin.com/in/medisetti-dhanush-9814a4381?utm_source=share_via&utm_content=profile&utm_medium=member_android",
    "instagramUrl": "https://www.instagram.com/dhanu_0318?stkn=dDd3MTdqMzNnaG85",
    "category": "Design"
  },
  {
    "id": "ca-15",
    "slug": "m-purnakanth",
    "name": "M Purnakanth",
    "teamIdBadge": "ST-CA-15",
    "role": "Campus Ambassador",
    "branch": "Mechanical Engineering \u00b7 Class of 2029",
    "college": "Anil neerukonda institute of technology and sciences",
    "location": "Sangivalasa",
    "phone": "6.309389573E9",
    "experience": "Official Student Tribe College Ambassador representing Anil neerukonda institute of technology and sciences (Sangivalasa). Spearheading Tribeverse engagement and campus community leadership.",
    "avatarUrl": "/id-cards-v2/m-purnakanth-front.png",
    "backAvatarUrl": "/id-cards-v2/m-purnakanth-back.png",
    "linkedinUrl": "https://www.linkedin.com/in/purna-kanth-m-959b65383/",
    "instagramUrl": "https://www.instagram.com/_______chandu_______76/",
    "category": "Core"
  },
  {
    "id": "ca-16",
    "slug": "k-manas",
    "name": "K.manas",
    "teamIdBadge": "ST-CA-16",
    "role": "Campus Ambassador",
    "branch": "Mechanical Engineering \u00b7 Class of 2029",
    "college": "Anil neerukonda institute of technology and sciences",
    "location": "Sangivalasa",
    "phone": "8.121381457E9",
    "experience": "Official Student Tribe College Ambassador representing Anil neerukonda institute of technology and sciences (Sangivalasa). Spearheading Tribeverse engagement and campus community leadership.",
    "avatarUrl": "/id-cards-v2/k-manas-front.png",
    "backAvatarUrl": "/id-cards-v2/k-manas-back.png",
    "linkedinUrl": "https://www.linkedin.com/in/manas-komma-8595ba423?utm_source=share_via&utm_content=profile&utm_medium=member_android",
    "instagramUrl": "https://www.instagram.com/manas_555_?stkn=OGlhd3oxd2gzMGdn",
    "category": "Core"
  },
  {
    "id": "ca-17",
    "slug": "sarika-manoj",
    "name": "Sarika Manoj",
    "teamIdBadge": "ST-CA-17",
    "role": "Campus Ambassador",
    "branch": "Mechanical Engineering \u00b7 Class of 2029",
    "college": "Anil neerukonda institute of technology and sciences",
    "location": "Sangivalasa",
    "phone": "9.381128773E9",
    "experience": "Official Student Tribe College Ambassador representing Anil neerukonda institute of technology and sciences (Sangivalasa). Spearheading Tribeverse engagement and campus community leadership.",
    "avatarUrl": "/id-cards-v2/sarika-manoj-front.png",
    "backAvatarUrl": "/id-cards-v2/sarika-manoj-back.png",
    "linkedinUrl": null,
    "instagramUrl": "https://www.instagram.com/_manoj_sarika/",
    "category": "Core"
  },
  {
    "id": "ca-18",
    "slug": "bobbadi-vamsi-rithvik",
    "name": "Bobbadi Vamsi Rithvik",
    "teamIdBadge": "ST-CA-18",
    "role": "Campus Ambassador",
    "branch": "Mechanical Engineering \u00b7 Class of 2029",
    "college": "Anil neerukonda institute of technology and sciences",
    "location": "Visakhapatnam",
    "phone": "7.794800102E9",
    "experience": "Official Student Tribe College Ambassador representing Anil neerukonda institute of technology and sciences (Visakhapatnam). Spearheading Tribeverse engagement and campus community leadership.",
    "avatarUrl": "/id-cards-v2/bobbadi-vamsi-rithvik-front.png",
    "backAvatarUrl": "/id-cards-v2/bobbadi-vamsi-rithvik-back.png",
    "linkedinUrl": "https://www.linkedin.com/in/vamsi-rithvik-265105381?utm_source=share_via&utm_content=profile&utm_medium=member_android",
    "instagramUrl": "https://www.instagram.com/vammmsii._?stkn=MTVqMDQ2ZHNjYzZ2eQ==",
    "category": "Core"
  },
  {
    "id": "ca-19",
    "slug": "barla-maanasa-reddy",
    "name": "Barla Maanasa Reddy",
    "teamIdBadge": "ST-CA-19",
    "role": "Campus Ambassador",
    "branch": "CSE (Computer Science) \u00b7 Class of 2029",
    "college": "Anil Neerukonda Institute of Technology and Sciences",
    "location": "Pedawaltair",
    "phone": "9.059961049E9",
    "experience": "Official Student Tribe College Ambassador representing Anil Neerukonda Institute of Technology and Sciences (Pedawaltair). Spearheading Tribeverse engagement and campus community leadership.",
    "avatarUrl": "/id-cards-v2/barla-maanasa-reddy-front.png",
    "backAvatarUrl": "/id-cards-v2/barla-maanasa-reddy-back.png",
    "linkedinUrl": "https://www.linkedin.com/in/barla-maanasa-reddy2812?utm_source=share_via&utm_content=profile&utm_medium=member_android",
    "instagramUrl": null,
    "category": "Core"
  }
];
